SET search_path TO public;

DROP TABLE IF EXISTS spol;
CREATE TABLE spol (
	id_spol INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	oznaka CHAR(1) UNIQUE NOT NULL
);

DROP TABLE IF EXISTS drzava;
CREATE TABLE drzava (
	id_drzava INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	naziv VARCHAR(128) UNIQUE NOT NULL,
	oznaka CHAR(2) UNIQUE NOT NULL
);

DROP TABLE IF EXISTS mjesto;
CREATE TABLE mjesto (
	id_mjesto INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	naziv VARCHAR(128) NOT NULL,
	post_br VARCHAR(10) NOT NULL,
	drzava_fk INT REFERENCES drzava(id_drzava)
);

DROP TABLE IF EXISTS radnik_vrsta;
CREATE TABLE radnik_vrsta (
	id_radnik_vrsta INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	naziv VARCHAR(64) UNIQUE NOT NULL
);

DROP TABLE IF EXISTS radno_mjesto;
CREATE TABLE radno_mjesto (
	id_radno_mjesto INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	naziv VARCHAR(128) UNIQUE NOT NULL
);

DROP TABLE IF EXISTS vrsta_radno_vrijeme;
CREATE TABLE vrsta_radno_vrijeme (
	id_vrsta_radno_vrijeme INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	naziv VARCHAR(128) UNIQUE NOT NULL
);

DROP TABLE IF EXISTS radno_vrijeme;
CREATE TABLE radno_vrijeme (
	id_radno_vrijeme INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	vrsta_radno_vrijeme_fk INT REFERENCES vrsta_radno_vrijeme(id_vrsta_radno_vrijeme) ON DELETE CASCADE,
	tjedno_sati DECIMAL (4,2) NOT NULL,
	dnevno_sati DECIMAL (3,2) NOT NULL,
	godisnji INT NOT NULL
);

DROP TABLE IF EXISTS vrsta_ugovor_rad;
CREATE TABLE vrsta_ugovor_rad (
	id_vrsta_ugovor_rad INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	naziv VARCHAR(128) UNIQUE NOT NULL
);

DROP TABLE IF EXISTS radnik;
CREATE TABLE radnik (
	id_radnik INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	radnik_nadred_fk INT REFERENCES radnik(id_radnik),
	ime VARCHAR(256) NOT NULL,
	prezime VARCHAR(256) NOT NULL,
	oib VARCHAR(11) NOT NULL,
	spol_fk INT REFERENCES spol(id_spol),
	datum_rod DATE NOT NULL,
	radnik_vrsta_fk INT REFERENCES radnik_vrsta(id_radnik_vrsta)
);

DROP TABLE IF EXISTS ugovor_rad;
CREATE TABLE ugovor_rad (
	id_ugovor_rad INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	radnik_fk INT UNIQUE REFERENCES radnik(id_radnik),
	datum_ugovor DATE NOT NULL,
	datum_od DATE NOT NULL,
	datum_do DATE,
	mjesto_rada_fk INT REFERENCES mjesto(id_mjesto),
	radno_mjesto_fk INT REFERENCES radno_mjesto(id_radno_mjesto),
	radno_vrijeme_fk INT REFERENCES radno_vrijeme(id_radno_vrijeme),
	vrsta_ugovor_rad_fk INT REFERENCES vrsta_ugovor_rad(id_vrsta_ugovor_rad),
	bruto_placa DECIMAL(10,2) NOT NULL
);

DROP TABLE IF EXISTS radnik_prebivaliste;
CREATE TABLE radnik_prebivaliste (
	id_radnik_prebivaliste INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	radnik_fk INT REFERENCES radnik(id_radnik),
	mjesto_fk INT REFERENCES mjesto(id_mjesto),
	ulica VARCHAR(128) NOT NULL,
	kucni_br VARCHAR(32) NOT NULL
);

DROP TABLE IF EXISTS evidencija_rad;
CREATE TABLE evidencija_rad (
	id_evidencija_rad INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	radnik_fk INT REFERENCES radnik(id_radnik),
	datum DATE NOT NULL,
	pocetak TIME NOT NULL,
	kraj TIME NOT NULL,
	ukupno_redovno DECIMAL (4,2) NOT NULL,
	redovno DECIMAL (4,2) NOT NULL,
	prekovr DECIMAL (4,2) NOT NULL,
	zastoj DECIMAL (4,2) NOT NULL,
	strajk DECIMAL (4,2) NOT NULL,
	lockout DECIMAL (4,2) NOT NULL,
	prerasp DECIMAL (4,2) NOT NULL,
	bol_do		_42 DECIMAL (4,2) NOT NULL,
	bol_od_42 DECIMAL (4,2) NOT NULL,
	godisnji DECIMAL (4,2) NOT NULL,
	godisnji_placen DECIMAL (4,2) NOT NULL,
	praznik DECIMAL (4,2) NOT NULL,
	ukupno_sati DECIMAL (4,2) NOT NULL,
	nedjelja_pov DECIMAL (4,2) NOT NULL,
	praznik_pov DECIMAL (4,2) NOT NULL,
	noc_pov DECIMAL (4,2) NOT NULL,
	smjena_pov DECIMAL (4,2) NOT NULL,
	dvokr_pov DECIMAL (4,2) NOT NULL,
	ostalo_pov DECIMAL (4,2) NOT NULL,
	pripr DECIMAL (4,2) NOT NULL,
	odmor DECIMAL (4,2) NOT NULL,
	odsut DECIMAL (4,2) NOT NULL
);

DROP TABLE IF EXISTS evidencija_snimka;
CREATE TABLE evidencija_snimka (
	id_evidencija_snimka INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	datum_od DATE NOT NULL,
	datum_do DATE NOT NULL,
	radnik_fk INT REFERENCES radnik(id_radnik),
	snimka BYTEA NOT NULL,
	datum DATE NOT NULL
);

DROP TABLE IF EXISTS odjel;
CREATE TABLE odjel (
	id_odjel INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	naziv VARCHAR(128) UNIQUE NOT NULL
);

DROP TABLE IF EXISTS radnik_odjel;
CREATE TABLE radnik_odjel (
	id_radnik_odjel INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	radnik_fk INT REFERENCES radnik(id_radnik),
	odjel_fk INT REFERENCES odjel(id_odjel),
	datum_od DATE NOT NULL,
	datum_do DATE
);